# episode 10 (NumPy)

In [1]:
import numpy as np

In [2]:
A=np.array([1,3,5])
A

array([1, 3, 5])

In [3]:
A.ndim #pour voir la dimension du tableau

1

In [4]:
A.shape #pour connaitre la taille du tableau

(3,)

In [5]:
A.nbytes

12

In [6]:
A.size #nous donne le nombre d'elements present dans notre tableau

3

In [7]:
B=np.zeros((3,2))
print(B)
print(B.ndim)
print(B.size)
print(B.nbytes)
print(type(B))
print(type(B.shape))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
2
6
48
<class 'numpy.ndarray'>
<class 'tuple'>


In [8]:
C=np.ones([3,4])
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
print(C.size)

12


In [10]:
D=np.full([2,3],5)
D

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
E=np.random.randn(3,4) #pour initialiser un tableau numpy avec des nombres aleatoires
E

array([[ 1.10467296, -0.59354259, -1.42356968,  0.70014987],
       [-0.13170761,  0.76900449, -0.83376185,  0.72471099],
       [-0.58044276, -0.44155731,  1.28310848, -0.85953795]])

In [20]:
np.random.seed(312098)
F=np.random.randn(3,4) 
F


array([[ 1.2824656 ,  0.70519288, -1.71966591, -0.96709965],
       [-0.03140678, -0.59476713,  0.59382329,  1.44692847],
       [ 0.00404294, -0.05312601, -0.96163844,  0.00219315]])

In [14]:
np.eye(5) #Pour creer une matrice identitre

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [41]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [46]:
np.arange(0,10,0.5,dtype=np.float16)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5], dtype=float16)

In [49]:
np.linspace(0,10,20,dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

## Manipulation

In [21]:
A=np.zeros([3,2])
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
B=np.ones([3,2])
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
C=np.hstack((A,B)) #assemblage de facon horizontal de A et B
print(C)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [24]:
C_1=np.hstack((B,A)) #assamblage de facon vertivcale de B et A
print((C_1))
print(C_1.size)
print(C_1.shape)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
12
(3, 4)


In [25]:
D=np.vstack((A,B)) #assamblage de facon verticale de A et B
print(D)
print(D.size)
print(D.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
12
(6, 2)


In [26]:
D_1=np.vstack((B,A)) #assamblage verticale de B et A
print(D_1)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
D=np.concatenate((A,B),axis=0)
print(D)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
C=np.concatenate((A,B), axis=1)
print(C)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [29]:
D=D.reshape((3,4)) #remanipuler la forme d'un tableau
print(D)

[[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
A=np.array([1,2,3])
A=A.reshape((A.shape[0],1))
A.shape

(3, 1)

In [32]:
A=A.squeeze()
A.shape

(3,)

In [33]:
D.ravel() #permet d'applatir un tableau en un tableau a une dimension

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

## Je m'exerce

In [34]:
import numpy as np


def initialisation(m,n):
    
    X=np.random.randn(m,n)
    
    X=np.concatenate((X,np.ones((X.shape[0],1))),axis=1)
    
    print( 'La forme de notre tableau est :', X.shape)
    
    return X


In [35]:
initialisation(3,4)

La forme de notre tableau est : (3, 5)


array([[ 1.92780973, -0.6122917 , -0.42280116,  1.13304654,  1.        ],
       [ 0.303195  , -0.06599947, -1.21112645,  0.60887159,  1.        ],
       [-0.44197869,  0.86964749, -0.15314301,  0.74931307,  1.        ]])