In [1]:
import numpy as np


In [2]:
np.random.seed(0)
A=np.random.randint(0,10,[5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

# Methode  ndarray

In [3]:
A.sum()

135

In [4]:
A.sum(axis=0)

array([32, 25, 31, 30, 17])

In [5]:
A.sum(axis=1)

array([18, 23, 30, 29, 35])

In [6]:
print(A.cumsum()) # somme cummule
print(A.cumsum(axis=0))
print(A.cumsum(axis=1))

[  5   5   8  11  18  27  30  35  37  41  48  54  62  70  71  77  84  91
  99 100 105 114 122 131 135]
[[ 5  0  3  3  7]
 [14  3  8  5 11]
 [21  9 16 13 12]
 [27 16 23 21 13]
 [32 25 31 30 17]]
[[ 5  5  8 11 18]
 [ 9 12 17 19 23]
 [ 7 13 21 29 30]
 [ 6 13 20 28 29]
 [ 5 14 22 31 35]]


In [7]:
print(A.prod())
print(A.cumprod())

0
[5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
print(A.min())
print(A.max())
print(A.min(axis=0))
print(A.max(axis=1))

0
9
[5 0 3 2 1]
[7 9 8 8 9]


In [9]:
# pouir trouver la positions des minimuns ou des maximuns
print(A.argmin(axis=1))
print(A.argmax(axis=0))

[1 3 4 4 4]
[1 4 2 4 0]


In [10]:
print(A)
A.argsort()

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]


array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3],
       [4, 0, 1, 2, 3],
       [4, 0, 2, 1, 3]], dtype=int64)

In [11]:
A.argsort(axis=0)

array([[0, 0, 0, 1, 2],
       [4, 1, 1, 0, 3],
       [3, 2, 3, 2, 1],
       [2, 3, 2, 3, 4],
       [1, 4, 4, 4, 0]], dtype=int64)

In [12]:
A.argsort(axis=1)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3],
       [4, 0, 1, 2, 3],
       [4, 0, 2, 1, 3]], dtype=int64)

In [13]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01, 2.00855369e+01,
        1.09663316e+03],
       [8.10308393e+03, 2.00855369e+01, 1.48413159e+02, 7.38905610e+00,
        5.45981500e+01],
       [1.09663316e+03, 4.03428793e+02, 2.98095799e+03, 2.98095799e+03,
        2.71828183e+00],
       [4.03428793e+02, 1.09663316e+03, 1.09663316e+03, 2.98095799e+03,
        2.71828183e+00],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 8.10308393e+03,
        5.45981500e+01]])

In [14]:
np.cos(A)

array([[ 0.28366219,  1.        , -0.9899925 , -0.9899925 ,  0.75390225],
       [-0.91113026, -0.9899925 ,  0.28366219, -0.41614684, -0.65364362],
       [ 0.75390225,  0.96017029, -0.14550003, -0.14550003,  0.54030231],
       [ 0.96017029,  0.75390225,  0.75390225, -0.14550003,  0.54030231],
       [ 0.28366219, -0.91113026, -0.14550003, -0.91113026, -0.65364362]])

# Statistiques

In [15]:
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [16]:
A.mean() #moyenne du tableau numpy A

5.4

In [17]:
A.var() #variance

7.12

In [18]:
A.std() #Ecart type

2.6683328128252666

In [19]:
np.corrcoef(A) #pour tracer une matrice de correlation pour notre tableau A

array([[ 1.        ,  0.39741307, -0.59190035, -0.77390599, -0.89934617],
       [ 0.39741307,  1.        ,  0.09521171, -0.11337365, -0.59181844],
       [-0.59190035,  0.09521171,  1.        ,  0.9579589 ,  0.6947088 ],
       [-0.77390599, -0.11337365,  0.9579589 ,  1.        ,  0.84515425],
       [-0.89934617, -0.59181844,  0.6947088 ,  0.84515425,  1.        ]])

In [20]:
np.corrcoef(A)[0,1]

0.39741306906256163

In [21]:
np.unique(A,return_counts=True) #pour connaitre les entites presents dans notre tableau ainsi que leur nombre

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64))

In [22]:
values,counts=np.unique(A,return_counts=True)

In [23]:
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64)

In [25]:
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int64)

In [26]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [27]:
for i,j in zip(values[counts.argsort()],counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


# NAN Corrections

In [28]:
A=np.random.randn(5,5) 
A[0,2]=np.nan  #NaN Not a Number
A[4,3]=np.nan
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [29]:
np.nanmean(A)  #elle va ignorer les NaNs

0.010707879575141632

In [30]:
np.nanvar(A)

1.213857100788078

In [31]:
np.nanstd(A)

1.1017518326683546

In [32]:
print(np.isnan(A)) #pour determiner le nombre de fois ou NAN apparait
np.isnan(A).sum()

[[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]]


2

In [33]:
np.isnan(A).sum()/A.size

0.08

In [34]:
A[np.isnan(A)]=0 #pour remplacer les valeurs de nan par 0
A

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

# Algebre Lineaire

In [35]:
A=np.ones((2,3))
B=np.ones((3,2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
A.T #transpose de la matrice A


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
A.dot(B) #produit matricielle A*B

array([[3., 3.],
       [3., 3.]])

In [39]:
B.dot(A) #produit matricielle B*A

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [40]:
A=np.random.randint(0,10,[3,3])
A

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [41]:
np.linalg.det(A) #pour determiner le determinant de A

23.999999999999993

In [42]:
np.linalg.inv(A) #pour determiner l'inverse de notre matrice A

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [-0.        ,  0.33333333, -0.33333333]])

In [43]:
np.linalg.pinv(A) #utiliser dans le ces des matricres avec des combinaisons lineaires entre les lingnes et les colonnes pour faire une pseudo inversion

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [ 0.        ,  0.33333333, -0.33333333]])

In [44]:
np.linalg.eig(A) #pour determiner les valeurs et les vecteurs propres de notre matrice

(array([13.58872344, -3.        , -0.58872344]),
 array([[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
        [-5.73889829e-01,  1.85511715e-16, -7.73940635e-01],
        [-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]))

In [45]:
# [13.58872344, -3.        , -0.58872344] sont les valeurs propres 
# et [[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
        #[-5.73889829e-01,  1.85511715e-16, -7.73940635e-01],
        #[-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]) 
 #sont les vecteurs propres

# Exercice

In [46]:
np.random.seed(0)
A=np.random.randint(0,100,[10,5])
A

#Standardisons colonne par colonne le tableau A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [47]:
#Solution 
B=(A-A.mean(axis=0))/A.std(axis=0)
B

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [48]:
print('la moyenne de chaque colonne :\n',B.mean(axis=0))
print('ecart type de chaque colonne :\n',B.std(axis=0))

la moyenne de chaque colonne :
 [-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]
ecart type de chaque colonne :
 [1. 1. 1. 1. 1.]
